### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Jakousa** [yusifsalam/voimanosto#2]
# Katselmointi

### Mitä tein

* 1.8.2019 klo ~14:00

* Rekisteröidyin ja kirjauduin sisään
  * Lisäsin kalenterissa "Log bodyweight"
  * Lisäsin kalenterissa "New workout"
  * Katselin käppyrää /profile sivulla
  * Epämääräistä klikkailua
  * Vaihdoin selaimen firefoxista chromeen ja tein samoja asioita

### Kokemus

* Toimiva sovellus jonka käyttö oli hetken opettelun jälkeen selkeämpää.

* Darkmode :heart-eyes:

* Polkujen käyttö mahdollisti bookmarkkauksen, mutta reactin favicon ja title "React App" kaipaa korjaamista.

* Jotain rikki GET https://voimanosto.herokuapp.com/api/users/jakousa/prs/sbd/Squat/Competition/current, välillä sain 500 vastauksen mutta huomattuani en pystynyt enää toistamaan. Liittynee uuteen käyttäjään esim uuden käyttäjän tehdessä workoutteja?

* Sivupalkkia ei varmaankaan syytä näyttää kirjaantumattomalle käyttäjälle. 

* Jotkin sivut täysin tyhjiä

* Koko käyttökokemus kaipaa hieman paddingiä / marginia. Tällä hetkellä kaikki on hieman vasemmassa yläreunassa. Erityisesti suuremmalla näytöllä > 1920x1080 käyttökokemus alkaa kärsiä.

* Hieno kalenteri, olisi kiva nähdä enemmän tietoja kalenterinäkymässä

## Koodi

* Typescript todella hyvä valinta vaikka aiheuttikin lisää työtunteja. 

* Kaikki kansiot ja tiedostot hyvin nimettyjä. Asiat löytyvät juuri sieltä mistä odottaisikin.

* ../../../../ vähentämiseksi on olemassa erilaisia ratkaisuja. Frontille on webpack resolve https://webpack.js.org/configuration/resolve/ ja backille mm. https://www.npmjs.com/package/module-alias

* Luettavuuden parantamiseksi suosittelen "portsaripatternia" https://refactoring.com/catalog/replaceNestedConditionalWithGuardClauses.html esimerkiksi https://github.com/yusifsalam/voimanosto/blob/master/voimanosto-backend/controllers/users.js tai https://github.com/yusifsalam/voimanosto/blob/master/voimanosto-frontend/src/components/Competition/Competition.tsx `if (!user) return`

* Tosin monissa esiintyvissä tapauksessa backissä kuten https://github.com/yusifsalam/voimanosto/blob/master/voimanosto-backend/controllers/exercises.js voit käyttää middlewarea säästämään copy-pastea.

## Kokonaisuus

* Projektissa on hieman keskeneräisyyden tuntua, mutta ratkaisut kuten typescript tukevat suurempia projekteja mainiosti.

* Hyvin rakennettu projekti, tästä on hyvä jatkaa.

💪  / 🏋️‍♀️

**Comment by yusifsalam** [comment]
Kiitos Jami kommenteista! 

> Polkujen käyttö mahdollisti bookmarkkauksen, mutta reactin favicon ja title "React App" kaipaa korjaamista.

Oops, tämä unohtunut. 

> Jotain rikki GET 

Kokeilin luoda uuden käyttäjän ja navigoimaan samaan polkuun, mutta en saanut poikkeusta toistettua.

> Jotkin sivut täysin tyhjiä

Under construction ™️.

> Koko käyttökokemus kaipaa hieman paddingiä / marginia. Tällä hetkellä kaikki on hieman vasemmassa yläreunassa. Erityisesti suuremmalla näytöllä > 1920x1080 käyttökokemus alkaa kärsiä.

Joo, itsellä selainikkuna aina about 1000x1440, siis en huomannut enkä testannut fullscreenkäyttöä.  

> Hieno kalenteri, olisi kiva nähdä enemmän tietoja kalenterinäkymässä

Tulossa pian. Ja kalenteri on macOS'in Calendar.app "inspired" 😆
![Screen Shot 2019-08-02 at 1 12 43](https://user-images.githubusercontent.com/42574232/62330900-c8fa1b00-b4c2-11e9-9239-3960ac92d617.png)


> Tosin monissa esiintyvissä tapauksessa backissä kuten https://github.com/yusifsalam/voimanosto/blob/master/voimanosto-backend/controllers/exercises.js voit käyttää middlewarea säästämään copy-pastea.

Kyllä, backend kaipaa refaktorointia, erityisesti POST metodit on liian pitkiä.  

> Projektissa on hieman keskeneräisyyden tuntua, mutta ratkaisut kuten typescript tukevat suurempia projekteja mainiosti

Joo, projekti on vielä kesken. Lisään seuraavaksi validointia kaikille lomakkeille ja käyttäjille analytiikkaa (Tools/Volume ja Tools/Intensity). 

> Hyvin rakennettu projekti, tästä on hyvä jatkaa.

Jees kiitos, jatkan tämän harrastusprojektina :) 

p.s. pushasin päivityksen herokuun ~18:00, nyt dashboard on hieman värikkäämpi.
